[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_factory = "xCtaFUv4D3NRP5NGvaf3uSSKgD1cbbi9mUaJgNJNYc1"

[programs.devnet]
token_factory = "7RSKqnZYg6wsPyHAjKK1i7RCYrYoyoSDw2AaPxMnAnWT"

[programs.mainnet]
token_factory = "xCtaFUv4D3NRP5NGvaf3uSSKgD1cbbi9mUaJgNJNYc1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/caseycharlesworth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
