[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_factory = "H7hosUTUzvSebYWvj4oFw8DrpjNZVAXBYNzAwZbaFcWg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/caseycharlesworth/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
